# -*- coding: utf-8 -*-
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('registerPage', views.registerPage, name='registerPage'),
    path('register', views.register, name='register'),
    path('login_password', views.login_password, name='login_password'),
    path('check_wx_login', views.check_wx_login, name='check_wx_login'),
    path('add_time', views.add_time, name='add_time'),
    path('create_cdkey', views.create_cdkey, name='create_cdkey'),
    path('get_cdkey', views.get_cdkey, name='get_cdkey'),
    path('refresh_uuid', views.refresh_uuid, name='refresh_uuid'),
    path('wx_logout', views.wx_logout, name='wx_logout'),
    path('room_data', views.room_data, name='room_data'),
    path('clear_room_data', views.clear_room_data, name='clear_room_data'),
    path('player_data', views.player_data, name='player_data'),
    path('add_player', views.add_player, name='add_player'),
    path('wechat_bind', views.wechat_bind, name='wechat_bind'),
    path('wrong_image', views.wrong_image, name='wrong_image'),
    path('setting', views.setting, name='setting'),
    path('update_cost_mode', views.update_cost_mode, name='update_cost_mode'),
    path('del_data', views.del_data, name='del_data'),
    path('player_stat', views.player_stat, name='player_stat'),
    path('clear_player_stat', views.clear_player_stat, name='clear_player_stat'),
    path('player_room_data', views.player_room_data, name='player_room_data'),
    path('delete_wrongimage', views.delete_wrongimage, name='delete_wrongimage'),
    path('add_score', views.add_score, name='add_score'),
    path('minus_score', views.minus_score, name='minus_score'),
    path('score_change', views.score_change, name='score_change'),
    path('score_change_log', views.score_change_log, name='score_change_log'),
    path('nick_players', views.nick_players, name='nick_players'),
    path('score_change_group', views.score_change_group, name='score_change_group'),
    path('save_captain', views.save_captain, name='save_captain'),
    path('append_member', views.append_member, name='append_member'),
    path('del_member', views.del_member, name='del_member'),
    path('add_gameid', views.add_gameid, name='add_gameid'),
    path('del_gameid', views.del_gameid, name='del_gameid'),
    path('wechat_friends', views.wechat_friends, name='wechat_friends'),
    path('stat_xls', views.stat_xls, name='stat_xls'),
    path('del_player', views.del_player, name='del_player'),
    path('change_passwd', views.change_passwd, name='change_passwd'),
    path('add_score_limit', views.add_score_limit, name='add_score_limit'),
    path('add_manager', views.add_manager, name='add_manager'),
    path('del_manager', views.del_manager, name='del_manager'),
    path('update_refresh_time', views.update_refresh_time, name='update_refresh_time'),
    path('generate_qrcode_p', views.generate_qrcode_p, name='generate_qrcode_p'),
    path('generate_qrcode_m', views.generate_qrcode_m, name='generate_qrcode_m'),
    path('qrcode_bind_p', views.qrcode_bind_p, name='qrcode_bind_['),
    path('qrcode_bind_m', views.qrcode_bind_m, name='qrcode_bind_m'),

    path('unbind_player', views.unbind_player, name='unbind_player'),
    path('unbind_manager', views.unbind_manager, name='unbind_manager'),
    path('rename_manager', views.rename_manager, name='rename_manager'),
    path('rename_player', views.rename_player, name='rename_player'),
    path('group_stat_xls', views.group_stat_xls, name='group_stat_xls'),

]