# Generated by Django 2.1.1 on 2018-09-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DServerAPP', '0002_auto_20180908_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='expiredTime',
            new_name='expired_time',
        ),
    ]
