# Generated by Django 2.1.1 on 2018-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DServerAPP', '0003_auto_20180911_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_Score',
        ),
        migrations.AddField(
            model_name='player',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='history_profit',
            field=models.IntegerField(default=0),
        ),
    ]
