# Generated by Django 2.1.1 on 2018-09-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DServerAPP', '0004_auto_20180922_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='introducer',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
