# Generated by Django 2.1.1 on 2018-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DServerAPP', '0005_player_introducer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='expired_time',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
    ]
