# Generated by Django 2.1.1 on 2018-09-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DServerAPP', '0006_auto_20180923_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10)),
                ('master_name', models.CharField(max_length=20)),
                ('round_number', models.IntegerField(default=0)),
                ('start_time', models.CharField(max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DServerAPP.Clubs')),
            ],
        ),
    ]
