# Generated by Django 2.1.1 on 2018-09-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DServerAPP', '0007_historygame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='introducer',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='wechat_nick_name',
            field=models.CharField(max_length=200),
        ),
    ]
