# Generated by Django 2.1.1 on 2018-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DServerAPP', '0008_auto_20180924_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameid',
            name='gameid',
            field=models.CharField(max_length=200),
        ),
    ]
